class: article
preamble: preamble.tex

chapter: Chapter 1
section: Files 1-3
    file: file-1
    file: file-2
    file: file-3
section: Files 4-7
    file: file-4
    file: file-5
    file: file-6
    file: file-7

chapter: Chapter 2
section: Files 8-10
    file: file-8
    file: file-9
    file: file-10

bib_style: plain
bibliography: sources.bib
