# Do not change this config file. 

class: notes
preamble: preamble.tex
handle_subsections: true

section: Voting Theory
    file: lecture-1.tex
    file: lecture-2.tex
    file: lecture-3.tex
    file: lecture-4.tex
section: Weighted Voting Theory
    file: lecture-5.tex
    file: lecture-6.tex
    file: lecture-7.tex
