preamble: preamble.tex

section: Vectors and Matrices
    file: lecture-1.tex
    file: lecture-2.tex
    file: lecture-3.tex

section: Row Reduction
    file: lecture-4.tex
    file: lecture-5.tex

preamble:
